# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\x1a\x1bgoogle/protobuf/empty.proto\".\n\x05Token\x12\x11\n\tuser_type\x18\x01 \x01(\x05\x12\x12\n\nsession_id\x18\x02 \x01(\t\",\n\x0c\x41uthResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t2<\n\x0b\x41uthService\x12-\n\x08\x41uthUser\x12\x0b.auth.Token\x1a\x12.auth.AuthResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOKEN']._serialized_start=49
  _globals['_TOKEN']._serialized_end=95
  _globals['_AUTHRESPONSE']._serialized_start=97
  _globals['_AUTHRESPONSE']._serialized_end=141
  _globals['_AUTHSERVICE']._serialized_start=143
  _globals['_AUTHSERVICE']._serialized_end=203
# @@protoc_insertion_point(module_scope)
